solver: mesh

mesh:
  element_type: q4

# Mesh generation sizes are in image pixels.
mesh_generation:
  method: auto

  element_type: q4

  target_element_size: 20.0

  fit_roi_boundary: true

  remove_outside_elements: true

  remove_outside_nodes: true

  allow_partial_elements: false

  min_element_quality: 0.1

optimization:
  method: global_icgn
  max_iterations: 30
  convergence_threshold: 1.0e-3
  regularization_alpha: 0.0

correlation:
  criterion: znssd

interpolation:
  method: bspline
  degree: 5

initialization:
  method: integer_search
  subset_radius: 10
  search_radius: 30
