"""Traditional-DIC Python API skeleton."""
from .subset import subset
from .mesh import mesh, generate_mesh_from_roi, generate_annulus_meshes_from_mask
from . import calibration
from .stereo import (
    reconstruct_from_field_files,
    reconstruct_from_fields,
    stereo,
)
from .multiview import (
    CameraPairSelectionOptions,
    PairMaskGenerationResult,
    Pairwise3DOptions,
    Pairwise3DRunResult,
    MultiviewScaleRecoveryOptions,
    MultiviewScaleRecoveryResult,
    PairwiseSurfaceStitchOptions,
    PairwiseSurfaceStitchRunResult,
    PairwiseDICOptions,
    PairwiseDICRunResult,
    MultiviewMaskOptions,
    compute_pairwise_2d_dic,
    compute_pairwise_3d_dic,
    generate_pair_masks_from_calibration,
    generate_masks_from_calibration,
    multiview,
    recover_multiview_calibration_scale,
    save_pair_selection_report,
    select_camera_pairs,
    stitch_pairwise_3d_surfaces,
)
from .config import load_config, normalize_mesh_config, normalize_subset_config
from .case import (
    CalibrationInput,
    CaseSpec,
    CameraRef,
    CaseResolutionError,
    FrameRef,
    ROIInput,
    ResolvedCase,
    ValidationIssue,
    ValidationResult,
    inspect_case,
    resolve_case,
    resolve_mono_case,
    resolve_multiview_case,
    resolve_stereo_case,
    validate_case,
)
from .config_resolver import (
    CONFIG_WORKFLOW_KINDS,
    ConfigIssue,
    ConfigResolutionError,
    ResolvedConfig,
    inspect_config,
    resolve_config,
    validate_config,
)
from . import visualization
from . import postprocess
from .run_contract import (
    SCHEMA_VERSION,
    FINAL_STATUSES,
    ArtifactDescriptor,
    RunContractError,
    RunWorkspace,
    finalize_run_contract,
    inspect_run,
    load_manifest,
    load_metrics,
    load_result,
    load_run,
    load_status,
    validate_run_contract,
)

__all__ = [
    "subset",
    "mesh",
    "generate_mesh_from_roi",
    "generate_annulus_meshes_from_mask",
    "calibration",
    "stereo",
    "reconstruct_from_fields",
    "reconstruct_from_field_files",
    "multiview",
    "generate_masks_from_calibration",
    "MultiviewMaskOptions",
    "CameraPairSelectionOptions",
    "PairMaskGenerationResult",
    "Pairwise3DOptions",
    "Pairwise3DRunResult",
    "MultiviewScaleRecoveryOptions",
    "MultiviewScaleRecoveryResult",
    "PairwiseSurfaceStitchOptions",
    "PairwiseSurfaceStitchRunResult",
    "PairwiseDICOptions",
    "PairwiseDICRunResult",
    "generate_pair_masks_from_calibration",
    "compute_pairwise_2d_dic",
    "compute_pairwise_3d_dic",
    "recover_multiview_calibration_scale",
    "stitch_pairwise_3d_surfaces",
    "select_camera_pairs",
    "save_pair_selection_report",
    "load_config",
    "normalize_mesh_config",
    "normalize_subset_config",
    "CalibrationInput",
    "CaseSpec",
    "CameraRef",
    "CaseResolutionError",
    "FrameRef",
    "ROIInput",
    "ResolvedCase",
    "ValidationIssue",
    "ValidationResult",
    "inspect_case",
    "resolve_case",
    "resolve_mono_case",
    "resolve_multiview_case",
    "resolve_stereo_case",
    "validate_case",
    "CONFIG_WORKFLOW_KINDS",
    "ConfigIssue",
    "ConfigResolutionError",
    "ResolvedConfig",
    "inspect_config",
    "resolve_config",
    "validate_config",
    "visualization",
    "postprocess",
    "SCHEMA_VERSION",
    "FINAL_STATUSES",
    "ArtifactDescriptor",
    "RunContractError",
    "RunWorkspace",
    "finalize_run_contract",
    "inspect_run",
    "load_manifest",
    "load_metrics",
    "load_result",
    "load_run",
    "load_status",
    "validate_run_contract",
]
