"""2D Subset-DIC Python API."""

from pathlib import Path
from typing import Optional, Union

import numpy as np

try:
    from . import _traditional_dic as _backend
    from .config import load_config, normalize_subset_config
    _has_backend = True
except ImportError:
    _has_backend = False


def subset(
    reference: np.ndarray,
    deformed: np.ndarray,
    config: Optional[Union[str, Path, dict]] = None,
    roi: Optional[np.ndarray] = None,
    # ---- Subset parameters ----
    radius: int = 15,
    # ---- Optimization ----
    max_iterations: int = 30,
    convergence_threshold: float = 1e-3,
    # ---- Interpolation ----
    bspline_degree: int = 5,
    # ---- Seed initialization ----
    search_radius: int = 20,
    seed_subset_radius: int = 10,
    sift_enabled: bool = False,
    pyramid_enabled: bool = True,
    subpixel_refinement: bool = True,
    # ---- Seed selection ----
    seed_count: int = 64,
    max_znssd: float = 0.3,
    min_displacement_norm: float = 0.0,
    min_texture_std: float = 0.02,
    # ---- Reliability propagation ----
    propagation_spacing: int = 5,
    propagation_max_znssd: float = 0.5,
):
    """
    Run 2D Subset-DIC with reliability-guided propagation.

    Parameters
    ----------
    reference : np.ndarray (H, W) float32 or float64
        Reference grayscale image, values in [0, 1].
    deformed : np.ndarray (H, W) float32 or float64
        Deformed image, same shape as reference.
    config : str, Path, dict, or None
        YAML file path, or a dict, or None to use explicit kwargs below.
        If both config and kwargs are provided, config takes precedence.
    roi : np.ndarray (H, W) bool or uint8, or None
        ROI mask. True/1 = inside ROI. None = full image.

    Subset parameters (used when config=None):
        radius : int = 15
            Subset radius in pixels.
        max_iterations : int = 30
            Maximum ICGN iterations per point.
        convergence_threshold : float = 1e-3
            ICGN convergence threshold (norm of delta parameter).
        bspline_degree : int = 5
            B-spline interpolation degree: 1, 3, or 5.

    Seed parameters (used when config=None):
        search_radius : int = 20
            Integer pixel search radius.
        seed_subset_radius : int = 10
            Subset radius for integer search.
        sift_enabled : bool = False
            Use SIFT matches as a displacement prior before local integer NCC.
        pyramid_enabled : bool = True
            Use pyramid/full-image NCC when SIFT prior is disabled.
        subpixel_refinement : bool = True
            Enable subpixel ICGN refinement for seeds.
        seed_count : int = 64
            Number of seed candidates generated by k-means.
        max_znssd : float = 0.3
            Maximum ZNSSD for seed quality pass.
        min_displacement_norm : float = 0.0
            Minimum displacement norm for seed selection (0 = any).
        min_texture_std : float = 0.02
            Minimum local texture standard deviation.

    Propagation parameters (used when config=None):
        propagation_spacing : int = 5
            Grid spacing in pixels for reliability propagation.
        propagation_max_znssd : float = 0.5
            Maximum ZNSSD accepted during reliability propagation.

    Returns
    -------
    dict of np.ndarray
        'x', 'y'       — grid point coordinates [px]
        'u', 'v'       — displacement [px]
        'du_dx', 'du_dy', 'dv_dx', 'dv_dy' — affine gradient params
        'correlation'  — ZNSSD
        'valid'        — bool
    """
    if not _has_backend:
        raise ImportError(
            "C++ backend _traditional_dic not found. "
            "Build with -DTRADITIONAL_DIC_BUILD_PYTHON=ON."
        )

    if not isinstance(reference, np.ndarray) or reference.ndim != 2:
        raise ValueError("reference must be a 2D numpy array")
    if not isinstance(deformed, np.ndarray) or deformed.ndim != 2:
        raise ValueError("deformed must be a 2D numpy array")
    if reference.shape != deformed.shape:
        raise ValueError("reference and deformed must have the same shape")

    # Build config dict from explicit kwargs, or from YAML/dict config
    if config is not None:
        if isinstance(config, (str, Path)):
            config_dict = normalize_subset_config(load_config(config))
        elif isinstance(config, dict):
            config_dict = normalize_subset_config(config)
        else:
            raise TypeError(f"config must be str, Path, dict, or None, got {type(config)}")
    else:
        # Assemble config dict from explicit kwargs with defaults
        config_dict = {
            "subset": {"radius": radius},
            "optimization": {
                "max_iterations": max_iterations,
                "convergence_threshold": convergence_threshold,
            },
            "interpolation": {"degree": bspline_degree},
            "initialization": {
                "method": "integer_search",
                "integer_search": {
                    "subset_radius": seed_subset_radius,
                    "search_radius": search_radius,
                    "sift_enabled": sift_enabled,
                    "pyramid_enabled": pyramid_enabled,
                },
                "subpixel_refinement": {
                    "enabled": subpixel_refinement,
                    "subset_radius": radius,
                    "max_iterations": max_iterations,
                    "convergence_threshold": convergence_threshold,
                },
            },
            "seed_selection": {
                "seed_count": seed_count,
                "max_znssd": max_znssd,
                "min_displacement_norm": min_displacement_norm,
                "min_texture_std": min_texture_std,
            },
            "reliability_propagation": {
                "spacing": propagation_spacing,
                "max_znssd": propagation_max_znssd,
            },
        }

    return _backend.subset.compute(reference, deformed, config_dict, roi)
