find_package(Eigen3 QUIET)
if(NOT Eigen3_FOUND)
    include(FetchContent)
    FetchContent_Declare(eigen URL https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz)
    FetchContent_MakeAvailable(eigen)
endif()
find_package(OpenCV QUIET)
find_package(pybind11 QUIET)
find_package(GTest QUIET)
